# Generated by Django 3.1 on 2023-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
    ]
