# Generated by Django 3.1 on 2023-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20230906_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
